name: Staging release

on:
    push:
        branches:
            - develop
jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout develop branch
              uses: actions/checkout@v2
            - name: Setup node 10.16.3
              uses: actions/setup-node@v1
              with:
                  node-version: 10.16.3
            - name: Build docker image
              run: docker build --tag weisong0908/coffee-shop-talk-vue-stg .
            - name: Login to Docker Hub with access token
              run: docker login -u weisong0908 -p ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
            - name: Push docker image to Docker Hub
              run: docker push weisong0908/coffee-shop-talk-vue-stg
    deploy:
        name: Deploy to server
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Executes remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DIGITALOCEAN_SERVERADDRESS }}
                  username: weisong0908
                  key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
                  port: 22
                  script: |
                      docker stop coffee-shop-talk-vue-stg
                      docker rm coffee-shop-talk-vue-stg
                      docker pull weisong0908/coffee-shop-talk-vue-stg
                      docker run -d -p 8080:8080 --name coffee-shop-talk-vue-stg weisong0908/coffee-shop-talk-vue-stg
